"""Add backref relationship to student

Revision ID: 2b13deca88f1
Revises: 8545b919c9ec
Create Date: 2023-04-20 15:32:12.104330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b13deca88f1'
down_revision = '8545b919c9ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
